backend:
  name: github
  branch: master
  repo: sserrata/docusaurus2
publish_mode: editorial_workflow
media_folder: "docs/assets"
collections:
  - name: "docs" # Used in routes, e.g., /admin/collections/blog
    label: "Docs" # Used in the UI
    folder: "docs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    identifier_field: id
    fields: # The fields for each document, usually in front matter
      - {label: "id", name: "id", widget: "string"} 
      - {label: "title", name: "title", widget: "string"}
      - {label: "sidebar_label", name: "sidebar_label", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
  - name: "sidebars"
    label: "Sidebars"
    create: false
    extension: yml
    files:
      - label: "Sidebars YAML"
        name: "sidebars"
        file: "docs/sidebars.yml"
        fields:
          - {label: Cateogry, name: category, widget: string}
          - label: IDs
            name: ids
            widget: list
            fields:
              - {label: id, name: id, widget: string}